---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/3/2025 3:58 PM
---

Entity.on {
    type = "Mob",

    onDamage = function(mob, damage)
        local health = mob:getHealth()

        local newHealth = health - damage

        mob:setHealth(newHealth)
    end
}