---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 7/31/2025 12:01 PM
---

Entity.on {
    type = "Player1",
    onDeath = function(self)
        print(self:getName() .. "was a good person.")
    end
}