---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/2/2025 11:45 AM
---

Vector3f = luajava.bindClass("org.joml.Vector3f")
PlayerClass = luajava.bindClass("net.adventuregame.player.Player")
InventoryClass = luajava.bindClass("net.adventuregame.player.Inventory")
EntityClass = luajava.bindClass("net.adventuregame.entity.Entity")
MultiMeshEntityClass = luajava.bindClass("net.adventuregame.entity.MultiMeshEntity")
MobClass = luajava.bindClass("net.adventuregame.mobs.Mob")
HostileMobClass = luajava.bindClass("net.adventuregame.mobs.hostile.HostileMob")
CutsceneClass = luajava.bindClass("net.adventuregame.cutscene.Cutscene")
CutsceneLineClass = luajava.bindClass("net.adventuregame.cutscene.CutsceneLine")
GUITextClass = luajava.bindClass("com.adv.core.font.GUIText")
ArrayListClass = luajava.bindClass("java.util.ArrayList")
ItemClass = luajava.bindClass("net.adventuregame.items.Item")
ItemEntityClass = luajava.bindClass("net.adventuregame.items.entities.ItemEntity")
QuestClass = luajava.bindClass("net.adventuregame.story.Quest")