---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 8/3/2025 2:21 PM
---

print("DEBUG Entity:", Entity)
print("DEBUG Entity.on:", Entity and Entity.on)
print("DEBUG Entity.on type:", type(Entity and Entity.on))