---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 7/31/2025 10:10 AM
---

Quest.add{
    id = "find_a_gun",
    description = "Defeat the beast in the cave.",
    condition = function()
        return Player.hasItem("pistol")
    end,
    onComplete = function()
        print("🔥 Quest Complete: kill_the_beast")
        Player.giveItem("katana")
    end
}