---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 7/31/2025 9:54 AM
---

Quest.add{
    id = "kill_the_beast",
    description = "Defeat the beast in the cave.",
    condition = function()
        return Player.hasKilled("cave_beast")
    end,
    onComplete = function()
        print("🔥 Quest Complete: kill_the_beast")
        Player.giveItem("trophy")
    end
}